project_id = "kcsvkdhnglpvzdvznmfs"

[functions.create-order]
verify_jwt = false

[functions.verify-sms]
verify_jwt = false

[functions.complete-order]
verify_jwt = false

[functions.download-pass]
verify_jwt = false

[functions.lookup-vehicle]
verify_jwt = false

[functions.send-email]
verify_jwt = false