name: Build Static Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Create www directory
      run: |
        mkdir -p www
        cp -r dist/* www/
    
    - name: Commit and push www folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add www/
        git diff --staged --quiet || git commit -m "Update static build files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}